### ISSUE TITLE
Request to port to perl

### ISSUE THREAD

**Issue by Norin-Radd** [higuita/vodafone.pt-xmltv#1] opened 2017-10-11 01:46 UTC
Hello,

I Have a request.

Since iam not a dev i would like to ask you if you can port this and submit it to xmltv.

I see that you already have this on your to do list.

I would be appreciated cause i don´t know how to use your script.

I would do it myself but i don´t have the right skill set.

I bet there will be more people who would benefit from your work.

thanks

**Comment by higuita** [comment] 2017-10-11 20:46
Hi

that is my idea, but i know more (linux and other unix like ) shell script than perl, so i have done this shell script first to test if i could import everything and get the xmltv programs i use to work.

now that i have found and fixed several small bugs, i think i'm ready to try the perl port... and yes, many people are waiting for something like this, i know several of them ;)

If you are using windows, you will have to wait for the perl ... if using linux, it is easy to run this, i can help you with the setup

**Comment by Norin-Radd** [comment] 2017-10-12 00:22
Iam using it on a QNAP Nas

It is linux, but iam using it alongside an xmltv and TvH app

**Comment by nsenica** [comment] 2017-12-14 12:51
Hi @higuita , I'm working on a xmltv "plugin" in perl, based on your shell script and findings.. It is still in development but close to an end, is this something you'd like to maintain and integrate here after I'm done ? :)

**Comment by Norin-Radd** [comment] 2017-12-15 23:16
@higuita at given horse you don´t look at his teeth! :P 

This can be a win win for us all, could you consider nsenica's offer?  :D

**Comment by higuita** [comment] 2017-12-17 23:59
Hi @nsenica 
Thanks a lot! Yes, i'm ready to maintain it here and, after some weeks of tests, do a pull request to the xmltv, so they can integrate it for everyone

**Comment by nsenica** [comment] 2017-12-18 08:00
Awesome :) 

Feel free to fork it from here (https://github.com/nsenica/xmltv) and do the PR. If you need any help, please let me know, I'm willing to help in anyway.

**Comment by nsenica** [comment] 2017-12-27 10:24
@higuita did you have the time to test it ?

**Comment by higuita** [comment] 2017-12-30 07:15
Hi @nsenica 
Sorry for the delay, busy with the Christmas and recompiling most of my perl modules due a distro perl upgrade! :)

I'm already testing and for now, looks good, the grabber works fine and the code is very clean, much better than my limited perl knowledge could do! :D

A little more tests later and i notice that you are trying to grab the season and episode, but i failed to see then in the xml... the i think the problem is in the code:

```
if ($title =~ m|\s+T\d+\s+-\s+Ep\.\s+\d+$|) {
```

well, using `|` as a delimiter is weird in regex, as it a special character... i recommend you to switch to `/` when possible, or `,` or `~` if the regex do have several `/`

but anyway, most^H^H^Hall examples i checked, the season/episode is in the ":T1 Ep.47" or " Ep2", so i made this changes locally and it worked fine:

```
    if ($title =~ m/(\s+|:)T\d+\s+-?\s*Ep\.\s*\d+$/) {
        # found season and episode in title
        my ($delimiter,$season, $episode) = ($title =~ m/(\s+|:)T(\d+)\s+-?\s*Ep\.\s*(\d+)$/);
#        $title =~ s/(\s+|:)T\d+\s+-?\s*Ep\.\s*\d+$//;
        $prog->{'episode-num'} =  [ [ ($season - 1).'.'.($episode-1).'.', 'xmltv_ns' ] ];
    } elsif ($title =~ m/\s+Ep\.\s*\d+$/) {
        # found episode in title
        my ($episode) = ($title =~ m/\s+Ep\.\s*(\d+)$/);
#        $title =~ s/\s+Ep\.\s*\d+$//;
        $prog->{'episode-num'} = [ [ '.'.($episode-1).'.', 'xmltv_ns' ] ];
    }
```
The `episode-num` show up now fine. I also commented the removal of the season and episode from the title, because at least one of my programs (tvtime) ignores the episode-num, so its hard to see what episode i'm seeing... other programs may also do the same, so removing that may not be helpful. Maybe a new option to enable/disable this removal is a good idea so people can tune the grabber for their software.

Finally,  the `--debug` option do not do anything, maybe is also a good idea to print to stderr the raw downloaded data in the `for my $channel` loop and in the `list_channels`. This may help debug any format change.

If you agree with the changes, i can do a pull request with my changes... but all this are small details, your work is awesome, thanks a lot for the correct xmltv grabber! :)

**Comment by higuita** [comment] 2017-12-30 17:38
i created a pull request: https://github.com/nsenica/xmltv/pull/1
i did try to add a new option for the full-title, but failed, not sure why... i may try again later

i notice that many of my comments are old code from pt_meo grabber, but i changed then anyway

**Comment by nsenica** [comment] 2017-12-31 14:11
Hi @higuita :)

Indeed I picked up pt_meo grabber and changed it to create this one.

I've checked your PR and it looks sane, thanks for taking the time to review it and improve it. It's very much appreciated.

Shall I do a PR to xmltv ?

Thanks

**Comment by higuita** [comment] 2018-01-03 21:15
@nsenica let me test it a little more (~1 week) , to see if i find any problem and if all is ok, lets do the PR to xmltv

**Comment by higuita** [comment] 2018-01-10 01:04
@nsenica new pull request (https://github.com/nsenica/xmltv/pull/2), i fixed some double `/` , inverted the wrong quiet flag and detect a obsolete channel id, that would make vodafone call to fail. The fix is to re-run the `--configure` to update the channel.conf

I think it is good to do a pull-request to xmltv and see what they say

**Comment by nsenica** [comment] 2018-01-10 08:14
Awesome :) Thank you very much for taking the time to test this.

I'll create the PR and we'll see. Thank you :)

**Comment by higuita** [comment] 2018-01-22 04:18
@nsenica great job! :)

@Norin-Radd XMLTV have merged the perl version of the vodafone grabber, if you have a up to date enogh xmltv version, you can download the file from https://github.com/XMLTV/xmltv/tree/master/grab/pt_vodafone and place it in your local install

**Closed as completed by higuita** 2018-01-22 04:18 UTC
